const PHONE_AMOUNT_OF_VIDEOS = 5;
const TABLET_AMOUNT_OF_VIDEOS = 8;
const LAPTOP_AMOUNT_OF_VIDEOS = 12;

export {
    PHONE_AMOUNT_OF_VIDEOS,
    TABLET_AMOUNT_OF_VIDEOS,
    LAPTOP_AMOUNT_OF_VIDEOS,
}